dirs:
  script_dir: occupationcoder/
  parent_dir: .
  lookup_dir: occupationcoder/dictionaries/
  output_dir: occupationcoder/outputs/

user:
  scheme: soc
  output: multi
  input_file: tests/test_vacancies.csv
  output_file: processed_jobs.csv
  title_column: job_title
  sector_column: job_sector
  description_column: job_description
