dirs:
  script_dir: .
  parent_dir: ..
  lookup_dir: dictionaries/
  output_dir: outputs/

user:
  scheme: soc
  output: multi
  # input_file: /path/to/your/data.csv   # leave blank to use bundled example
  output_file: processed_jobs.csv
  title_column: job_title
  sector_column: job_sector
  description_column: job_description
