dirs:
  script_dir: .
  parent_dir: ..
  lookup_dir: dictionaries/
  output_dir: outputs/

user:
  scheme: soc
  output: multi
  input_file: tests/test_vacancies.csv
  output_file: processed_jobs.csv
  title_column: job_title
  sector_column: job_sector
  description_column: job_description
